# Generated by Django 4.2.3 on 2023-07-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPost',
        ),
    ]
