# Generated by Django 4.2.3 on 2023-08-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_delete_topic_alter_product_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Content',
        ),
    ]
