# Generated by Django 4.2.3 on 2023-08-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0008_remove_content_image_remove_content_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/'),
        ),
    ]
