# Generated by Django 4.2.3 on 2023-08-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
